shaarli:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: shaarli
        hajimari.io/icon: google-drive
      hosts:
        - host: &host shaarli.mcp.cool
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: shaarli-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      type: pvc
      namespace: shaarli
      labels:
        label1: value1
      annotations:
        annotation1: value1
        pv.beta.kubernetes.io/gid: "101"
        volume.beta.kubernetes.io/mount-options: "uid=100,gid=101"
#      accessModes: ReadWriteOnce
#      volumeName: volume-name-backing-the-pvc
#      existingClaim: existing-claim-name
      retain: true
      size: 5Gi
      targetSelectAll: true
    cache:
      enabled: true
      type: pvc
      namespace: shaarli
      labels:
        label1: value2
      annotations:
        annotation1: value2
        pv.beta.kubernetes.io/gid: "101"
        volume.beta.kubernetes.io/mount-options: "uid=100,gid=101"
#      accessModes: ReadWriteOnce
#      volumeName: volume-name-backing-the-pvc
#      existingClaim: existing-claim-name
      retain: true
      size: 5Gi
      targetSelectAll: true
