shaarli:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: shaarli
        hajimari.io/icon: google-drive
      hosts:
        - host: &host shaarli.mcp.cool
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: shaarli-tls-certificate
          hosts:
            - *host

#https://truecharts.org/manual/helm/common/persistence/pvc/
#/var/www # chown 100:101 shaarli/data
#chown 100:101 shaarli/cache
#chmod 755 shaarli/data
#chmod 755 shaarli/cache
  persistence:
    data:
      enabled: true
      type: pvc
      namespace: shaarli
      labels:
        label1: value1
      annotations:
        annotation1: value1
#      accessModes: ReadWriteOnce
#      volumeName: volume-name-backing-the-pvc
#      existingClaim: existing-claim-name
      retain: true
      size: 5Gi
      targetSelectAll: true
    cache:
      enabled: true
      type: pvc
      namespace: shaarli
      labels:
        label1: value2
      annotations:
        annotation1: value2
#      accessModes: ReadWriteOnce
#      volumeName: volume-name-backing-the-pvc
#      existingClaim: existing-claim-name
      retain: true
      size: 5Gi
      targetSelectAll: true
