shaarli:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: shaarli
        hajimari.io/icon: google-drive
      hosts:
        - host: &host shaarli.mcp.cool
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: shaarli-tls-certificate
          hosts:
            - *host