nextcloud:
  ingress:
    enabled: true
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: nextcloud
        hajimari.io/icon: google-drive
      hosts:
        - host: &host nextcloud.mcp.cool
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: nextcloud-tls-certificate
          hosts:
            - *host

#https://truecharts.org/manual/helm/common/persistence/pvc/
  persistence:
    enabled: true
    # html:
    #   enabled: true
    #   type: pvc
    #   namespace: nextcloud
    #   size: 5Gi
    #   targetSelectAll: true
    # config:
    #   enabled: true
    #   type: pvc
    #   namespace: nextcloud
    #   size: 5Gi
    #   targetSelectAll: true
    # data:
    #   enabled: true
    #   type: pvc
    #   namespace: nextcloud
    #   size: 5Gi
    #   targetSelectAll: true
