cloudnative-pg:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: cloudnative-pg
        hajimari.io/icon: google-drive
      hosts:
        - host: &host cloudnative-pg.mcp.cool
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: cloudnative-pg-tls-certificate
          hosts:
            - *host

#https://truecharts.org/manual/helm/common/persistence/pvc/
  persistence:
    scratch-data:
      enabled: true
      type: pvc
      namespace: cloudnative-pg
      labels:
        label1: value1
      annotations:
        annotation1: value1
#      accessModes: ReadWriteOnce
#      volumeName: volume-name-backing-the-pvc
#      existingClaim: existing-claim-name
      retain: true
      size: 5Gi
      targetSelectAll: true
