pgadmin:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: pgadmin
        hajimari.io/icon: google-drive
      hosts:
        - host: &host pgadmin.mcp.cool
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: pgadmin-tls-certificate
          hosts:
            - *host

#https://truecharts.org/manual/helm/common/persistence/pvc/
  persistence:
    config:
      enabled: true
      type: pvc
      namespace: pgadmin
      labels:
        label1: value1
      annotations:
        annotation1: value1
      retain: true
      size: 1Gi
      targetSelectAll: true
