ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 45
#      worker-shutdown-timeout: 900s
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
